"""ISO country codes -> readable names, 3-letter codes and flag emoji.

OpenAlex stores institution countries as 2-letter ISO codes ("PK", "CA").
The app needs a readable name for the dropdown and a 3-letter code for the
world map, so both live here. Generated once from the ISO 3166 list; no
internet or extra package is needed at runtime.
"""
from __future__ import annotations

COUNTRIES: dict[str, tuple[str, str]] = {
    "AD": ("Andorra", "AND"),
    "AE": ("United Arab Emirates", "ARE"),
    "AF": ("Afghanistan", "AFG"),
    "AG": ("Antigua and Barbuda", "ATG"),
    "AI": ("Anguilla", "AIA"),
    "AL": ("Albania", "ALB"),
    "AM": ("Armenia", "ARM"),
    "AO": ("Angola", "AGO"),
    "AQ": ("Antarctica", "ATA"),
    "AR": ("Argentina", "ARG"),
    "AS": ("American Samoa", "ASM"),
    "AT": ("Austria", "AUT"),
    "AU": ("Australia", "AUS"),
    "AW": ("Aruba", "ABW"),
    "AX": ("Åland Islands", "ALA"),
    "AZ": ("Azerbaijan", "AZE"),
    "BA": ("Bosnia and Herzegovina", "BIH"),
    "BB": ("Barbados", "BRB"),
    "BD": ("Bangladesh", "BGD"),
    "BE": ("Belgium", "BEL"),
    "BF": ("Burkina Faso", "BFA"),
    "BG": ("Bulgaria", "BGR"),
    "BH": ("Bahrain", "BHR"),
    "BI": ("Burundi", "BDI"),
    "BJ": ("Benin", "BEN"),
    "BL": ("Saint Barthélemy", "BLM"),
    "BM": ("Bermuda", "BMU"),
    "BN": ("Brunei Darussalam", "BRN"),
    "BO": ("Bolivia", "BOL"),
    "BQ": ("Bonaire, Sint Eustatius and Saba", "BES"),
    "BR": ("Brazil", "BRA"),
    "BS": ("Bahamas", "BHS"),
    "BT": ("Bhutan", "BTN"),
    "BV": ("Bouvet Island", "BVT"),
    "BW": ("Botswana", "BWA"),
    "BY": ("Belarus", "BLR"),
    "BZ": ("Belize", "BLZ"),
    "CA": ("Canada", "CAN"),
    "CC": ("Cocos (Keeling) Islands", "CCK"),
    "CD": ("Congo, The Democratic Republic of the", "COD"),
    "CF": ("Central African Republic", "CAF"),
    "CG": ("Congo", "COG"),
    "CH": ("Switzerland", "CHE"),
    "CI": ("Côte d'Ivoire", "CIV"),
    "CK": ("Cook Islands", "COK"),
    "CL": ("Chile", "CHL"),
    "CM": ("Cameroon", "CMR"),
    "CN": ("China", "CHN"),
    "CO": ("Colombia", "COL"),
    "CR": ("Costa Rica", "CRI"),
    "CU": ("Cuba", "CUB"),
    "CV": ("Cabo Verde", "CPV"),
    "CW": ("Curaçao", "CUW"),
    "CX": ("Christmas Island", "CXR"),
    "CY": ("Cyprus", "CYP"),
    "CZ": ("Czechia", "CZE"),
    "DE": ("Germany", "DEU"),
    "DJ": ("Djibouti", "DJI"),
    "DK": ("Denmark", "DNK"),
    "DM": ("Dominica", "DMA"),
    "DO": ("Dominican Republic", "DOM"),
    "DZ": ("Algeria", "DZA"),
    "EC": ("Ecuador", "ECU"),
    "EE": ("Estonia", "EST"),
    "EG": ("Egypt", "EGY"),
    "EH": ("Western Sahara", "ESH"),
    "ER": ("Eritrea", "ERI"),
    "ES": ("Spain", "ESP"),
    "ET": ("Ethiopia", "ETH"),
    "FI": ("Finland", "FIN"),
    "FJ": ("Fiji", "FJI"),
    "FK": ("Falkland Islands (Malvinas)", "FLK"),
    "FM": ("Micronesia, Federated States of", "FSM"),
    "FO": ("Faroe Islands", "FRO"),
    "FR": ("France", "FRA"),
    "GA": ("Gabon", "GAB"),
    "GB": ("United Kingdom", "GBR"),
    "GD": ("Grenada", "GRD"),
    "GE": ("Georgia", "GEO"),
    "GF": ("French Guiana", "GUF"),
    "GG": ("Guernsey", "GGY"),
    "GH": ("Ghana", "GHA"),
    "GI": ("Gibraltar", "GIB"),
    "GL": ("Greenland", "GRL"),
    "GM": ("Gambia", "GMB"),
    "GN": ("Guinea", "GIN"),
    "GP": ("Guadeloupe", "GLP"),
    "GQ": ("Equatorial Guinea", "GNQ"),
    "GR": ("Greece", "GRC"),
    "GS": ("South Georgia and the South Sandwich Islands", "SGS"),
    "GT": ("Guatemala", "GTM"),
    "GU": ("Guam", "GUM"),
    "GW": ("Guinea-Bissau", "GNB"),
    "GY": ("Guyana", "GUY"),
    "HK": ("Hong Kong", "HKG"),
    "HM": ("Heard Island and McDonald Islands", "HMD"),
    "HN": ("Honduras", "HND"),
    "HR": ("Croatia", "HRV"),
    "HT": ("Haiti", "HTI"),
    "HU": ("Hungary", "HUN"),
    "ID": ("Indonesia", "IDN"),
    "IE": ("Ireland", "IRL"),
    "IL": ("Israel", "ISR"),
    "IM": ("Isle of Man", "IMN"),
    "IN": ("India", "IND"),
    "IO": ("British Indian Ocean Territory", "IOT"),
    "IQ": ("Iraq", "IRQ"),
    "IR": ("Iran", "IRN"),
    "IS": ("Iceland", "ISL"),
    "IT": ("Italy", "ITA"),
    "JE": ("Jersey", "JEY"),
    "JM": ("Jamaica", "JAM"),
    "JO": ("Jordan", "JOR"),
    "JP": ("Japan", "JPN"),
    "KE": ("Kenya", "KEN"),
    "KG": ("Kyrgyzstan", "KGZ"),
    "KH": ("Cambodia", "KHM"),
    "KI": ("Kiribati", "KIR"),
    "KM": ("Comoros", "COM"),
    "KN": ("Saint Kitts and Nevis", "KNA"),
    "KP": ("North Korea", "PRK"),
    "KR": ("South Korea", "KOR"),
    "KW": ("Kuwait", "KWT"),
    "KY": ("Cayman Islands", "CYM"),
    "KZ": ("Kazakhstan", "KAZ"),
    "LA": ("Laos", "LAO"),
    "LB": ("Lebanon", "LBN"),
    "LC": ("Saint Lucia", "LCA"),
    "LI": ("Liechtenstein", "LIE"),
    "LK": ("Sri Lanka", "LKA"),
    "LR": ("Liberia", "LBR"),
    "LS": ("Lesotho", "LSO"),
    "LT": ("Lithuania", "LTU"),
    "LU": ("Luxembourg", "LUX"),
    "LV": ("Latvia", "LVA"),
    "LY": ("Libya", "LBY"),
    "MA": ("Morocco", "MAR"),
    "MC": ("Monaco", "MCO"),
    "MD": ("Moldova", "MDA"),
    "ME": ("Montenegro", "MNE"),
    "MF": ("Saint Martin (French part)", "MAF"),
    "MG": ("Madagascar", "MDG"),
    "MH": ("Marshall Islands", "MHL"),
    "MK": ("North Macedonia", "MKD"),
    "ML": ("Mali", "MLI"),
    "MM": ("Myanmar", "MMR"),
    "MN": ("Mongolia", "MNG"),
    "MO": ("Macao", "MAC"),
    "MP": ("Northern Mariana Islands", "MNP"),
    "MQ": ("Martinique", "MTQ"),
    "MR": ("Mauritania", "MRT"),
    "MS": ("Montserrat", "MSR"),
    "MT": ("Malta", "MLT"),
    "MU": ("Mauritius", "MUS"),
    "MV": ("Maldives", "MDV"),
    "MW": ("Malawi", "MWI"),
    "MX": ("Mexico", "MEX"),
    "MY": ("Malaysia", "MYS"),
    "MZ": ("Mozambique", "MOZ"),
    "NA": ("Namibia", "NAM"),
    "NC": ("New Caledonia", "NCL"),
    "NE": ("Niger", "NER"),
    "NF": ("Norfolk Island", "NFK"),
    "NG": ("Nigeria", "NGA"),
    "NI": ("Nicaragua", "NIC"),
    "NL": ("Netherlands", "NLD"),
    "NO": ("Norway", "NOR"),
    "NP": ("Nepal", "NPL"),
    "NR": ("Nauru", "NRU"),
    "NU": ("Niue", "NIU"),
    "NZ": ("New Zealand", "NZL"),
    "OM": ("Oman", "OMN"),
    "PA": ("Panama", "PAN"),
    "PE": ("Peru", "PER"),
    "PF": ("French Polynesia", "PYF"),
    "PG": ("Papua New Guinea", "PNG"),
    "PH": ("Philippines", "PHL"),
    "PK": ("Pakistan", "PAK"),
    "PL": ("Poland", "POL"),
    "PM": ("Saint Pierre and Miquelon", "SPM"),
    "PN": ("Pitcairn", "PCN"),
    "PR": ("Puerto Rico", "PRI"),
    "PS": ("Palestine, State of", "PSE"),
    "PT": ("Portugal", "PRT"),
    "PW": ("Palau", "PLW"),
    "PY": ("Paraguay", "PRY"),
    "QA": ("Qatar", "QAT"),
    "RE": ("Réunion", "REU"),
    "RO": ("Romania", "ROU"),
    "RS": ("Serbia", "SRB"),
    "RU": ("Russian Federation", "RUS"),
    "RW": ("Rwanda", "RWA"),
    "SA": ("Saudi Arabia", "SAU"),
    "SB": ("Solomon Islands", "SLB"),
    "SC": ("Seychelles", "SYC"),
    "SD": ("Sudan", "SDN"),
    "SE": ("Sweden", "SWE"),
    "SG": ("Singapore", "SGP"),
    "SH": ("Saint Helena, Ascension and Tristan da Cunha", "SHN"),
    "SI": ("Slovenia", "SVN"),
    "SJ": ("Svalbard and Jan Mayen", "SJM"),
    "SK": ("Slovakia", "SVK"),
    "SL": ("Sierra Leone", "SLE"),
    "SM": ("San Marino", "SMR"),
    "SN": ("Senegal", "SEN"),
    "SO": ("Somalia", "SOM"),
    "SR": ("Suriname", "SUR"),
    "SS": ("South Sudan", "SSD"),
    "ST": ("Sao Tome and Principe", "STP"),
    "SV": ("El Salvador", "SLV"),
    "SX": ("Sint Maarten (Dutch part)", "SXM"),
    "SY": ("Syria", "SYR"),
    "SZ": ("Eswatini", "SWZ"),
    "TC": ("Turks and Caicos Islands", "TCA"),
    "TD": ("Chad", "TCD"),
    "TF": ("French Southern Territories", "ATF"),
    "TG": ("Togo", "TGO"),
    "TH": ("Thailand", "THA"),
    "TJ": ("Tajikistan", "TJK"),
    "TK": ("Tokelau", "TKL"),
    "TL": ("Timor-Leste", "TLS"),
    "TM": ("Turkmenistan", "TKM"),
    "TN": ("Tunisia", "TUN"),
    "TO": ("Tonga", "TON"),
    "TR": ("Türkiye", "TUR"),
    "TT": ("Trinidad and Tobago", "TTO"),
    "TV": ("Tuvalu", "TUV"),
    "TW": ("Taiwan", "TWN"),
    "TZ": ("Tanzania", "TZA"),
    "UA": ("Ukraine", "UKR"),
    "UG": ("Uganda", "UGA"),
    "UM": ("United States Minor Outlying Islands", "UMI"),
    "US": ("United States", "USA"),
    "UY": ("Uruguay", "URY"),
    "UZ": ("Uzbekistan", "UZB"),
    "VA": ("Holy See (Vatican City State)", "VAT"),
    "VC": ("Saint Vincent and the Grenadines", "VCT"),
    "VE": ("Venezuela", "VEN"),
    "VG": ("Virgin Islands, British", "VGB"),
    "VI": ("Virgin Islands, U.S.", "VIR"),
    "VN": ("Vietnam", "VNM"),
    "VU": ("Vanuatu", "VUT"),
    "WF": ("Wallis and Futuna", "WLF"),
    "WS": ("Samoa", "WSM"),
    "YE": ("Yemen", "YEM"),
    "YT": ("Mayotte", "MYT"),
    "ZA": ("South Africa", "ZAF"),
    "ZM": ("Zambia", "ZMB"),
    "ZW": ("Zimbabwe", "ZWE"),
    "XK": ("Kosovo", "XKX"),
}


def _clean(code) -> str:
    """Accept anything the database can return: 'pk', None, or pandas NaN
    (a float!) for authors whose institution has no country."""
    if not isinstance(code, str):
        return ""
    return code.strip().upper()


def name(code: str | None) -> str:
    code = _clean(code)
    if not code:
        return "Unknown"
    return COUNTRIES.get(code.upper(), (code.upper(), ""))[0]


def iso3(code: str | None) -> str:
    code = _clean(code)
    if not code:
        return ""
    return COUNTRIES.get(code.upper(), ("", ""))[1]


def flag(code: str | None) -> str:
    """'PK' -> the Pakistan flag emoji (two regional-indicator letters)."""
    code = _clean(code)
    if len(code) != 2 or not code.isalpha():
        return "🏳️"
    return "".join(chr(0x1F1E6 + ord(ch) - ord("A")) for ch in code.upper())


def label(code: str | None) -> str:
    if not _clean(code):
        return "—  Unknown"
    return f"{flag(code)}  {name(code)}"
